<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="repositorymodel" nsURI="http://hub.sam.repositorymodel/1.0/emffrag"
    nsPrefix="repositorymodel">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="java" value="../../../plugin/org.eclipse.gmt.modisco.java/model/java.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryModel" eSuperTypes="#//DirectoryElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRefs" upperBound="-1"
        eType="#//Ref" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRevs" upperBound="-1"
        eType="#//Rev" containment="true">
      <eAnnotations source="de.hub.emffrag">
        <details key="fragments" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootRevs" upperBound="-1"
        eType="#//Rev"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traversals" eType="#//TraversalState"
        containment="true">
      <eAnnotations source="de.hub.emffrag">
        <details key="Fragmentation" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaData" eType="#//RepositoryMetaData"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rev">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentRelations" upperBound="-1"
        eType="#//ParentRelation" containment="true" eOpposite="#//ParentRelation/child"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childRelations" upperBound="-1"
        eType="#//ParentRelation" eOpposite="#//ParentRelation/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importErrors" upperBound="-1"
        eType="#//ImportError" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ref">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedCommit" eType="#//Rev"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPeeled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSymbolic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diff">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ChangeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" eType="#//AbstractFileRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ChangeType" instanceClassName="org.eclipse.jgit.diff.DiffEntry.ChangeType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParentRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffs" upperBound="-1"
        eType="#//Diff" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Rev"
        eOpposite="#//Rev/childRelations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//Rev" eOpposite="#//Rev/parentRelations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFileRef" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaCompilationUnitRef" eSuperTypes="#//AbstractFileRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compilationUnitModel" eType="#//CompilationUnitModel"
        containment="true">
      <eAnnotations source="de.hub.emffrag">
        <details key="fragments" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraversalState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="merges" upperBound="-1"
        eType="#//Rev"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="openBranches" upperBound="-1"
        eType="#//Rev"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="completedBranches" upperBound="-1"
        eType="#//Rev"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfImportedRevs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PendingElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientNode" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//ASTNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Target">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompilationUnitModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compilationUnit" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//CompilationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="javaModel" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//Model"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pendings" upperBound="-1"
        eType="#//PendingElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="#//Target" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportError">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conrolled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exceptionClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryMetaData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldestRev" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newestRev" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cuCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workingCopy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revsWithErrors" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataStoreMetaData" eType="#//DataStoreMetaData"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importMetaData" eType="#//ImportMetaData"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryModelDirectory" eSuperTypes="#//DirectoryElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositories" upperBound="-1"
        eType="#//RepositoryModel" containment="true">
      <eAnnotations source="de.hub.emffrag">
        <details key="Fragmentation" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subDirectories" upperBound="-1"
        eType="#//RepositoryModelDirectory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduledForImport" upperBound="-1"
        eType="#//RepositoryModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imported" upperBound="-1"
        eType="#//RepositoryModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataStoreMetaData" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MongoDBMetaData" eSuperTypes="#//DataStoreMetaData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="avgObjectSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storeSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="server" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectoryElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportMetaData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importStats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importStatsAsJSON" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
